create table users (
  id bigint generated by default as identity primary key,
  nome varchar not null,
  email varchar not null,
  senha varchar not null,
  data_nascimento date not null,
  status boolean not null
);

create table events (
  id bigint generated by default as identity primary key,
  nome varchar not null,
  email varchar not null,
  senha varchar not null,
  dia varchar not null,
  user_id bigint not null,
  foreign key (user_id) references users(id)
);

create table tasks (
  id bigint generated by default as identity primary key,
  nome varchar not null,
  tamanho varchar not null,
  tempo_duracao numeric not null,
  descricao text not null,
  user_id bigint not null,
  foreign key (user_id) references users(id)
);
